### ISSUE TITLE
React Native - Multiple commands produce header files

### ISSUE THREAD

**Issue by degiepet89** [Nets-eCom/Nets-Easy-iOS-SDK#31] opened 2022-10-10 09:49 UTC
Hello, I have a issue with integrating mia for react native. Followed the instructions for SDK version 1.6, autolinking works, but in some part of build phase it ends with error:

Multiple commands produce '/Users/***/Library/Developer/Xcode/DerivedData/***-dzbgrdhclhjyxlgkranvlqpssdqw/Build/Products/Debug-iphoneos/react-native-rn-mia/react_native_rn_mia.framework/Headers/MIAPaymentInfo.h'

- Target 'react-native-rn-mia' (project 'Pods') has copy command from '/Users/***/IdeaProjects/***/***/node_modules/react-native-rn-mia/ios/Mia.framework/PrivateHeaders/MIAPaymentInfo.h' to '/Users/***/Library/Developer/Xcode/DerivedData/***-dzbgrdhclhjyxlgkranvlqpssdqw/Build/Products/Debug-iphoneos/react-native-rn-mia/react_native_rn_mia.framework/Headers/MIAPaymentInfo.h'
- Target 'react-native-rn-mia' (project 'Pods') has copy command from '/Users/***/IdeaProjects/***/***/node_modules/react-native-rn-mia/ios/Mia.xcframework/ios-arm64_armv7_armv7s/Mia.framework/PrivateHeaders/MIAPaymentInfo.h' to '/Users/***/Library/Developer/Xcode/DerivedData/***-dzbgrdhclhjyxlgkranvlqpssdqw/Build/Products/Debug-iphoneos/react-native-rn-mia/react_native_rn_mia.framework/Headers/MIAPaymentInfo.h'
- Target 'react-native-rn-mia' (project 'Pods') has copy command from '/Users/***/IdeaProjects/***/***/node_modules/react-native-rn-mia/ios/Mia.xcframework/ios-arm64_i386_x86_64-simulator/Mia.framework/PrivateHeaders/MIAPaymentInfo.h' to '/Users/***/Library/Developer/Xcode/DerivedData/***-dzbgrdhclhjyxlgkranvlqpssdqw/Build/Products/Debug-iphoneos/react-native-rn-mia/react_native_rn_mia.framework/Headers/MIAPaymentInfo.h'

Using:
RN17
XCode version 13.4.1 - New build system

**Comment by Miss-PiA** [comment] 2022-10-13 10:38
Hi Degiepet,

On our side we tried running the project it ran properly our **react version is 17.0.1**, **react-native: 0.67.0**, and we are using **Xcode 13.4.1** with the **New Build System.**
So could please check the below information and make changes if possible and let us know if the error is resolved or not 
 1. if you are using the Apple M1 chip make the architecture in build settings to arm64 
 2 Please also check any duplicate files in the Build phases of the target of the project **(Build Phases > Copy Bundle 
        Resources)** or duplicate code in **(Build Phase > [CP] Copy Pods Resources)** please remove them and build it 
        again.
3. Also, try re-installing pods again the issue might get resolved.
Also possibly could please send us the screenshots or a small-step video doing the integration process so we can go into more details?
Please let us know in case of any issues.

Thanks & Regards

**Comment by Nets-in-app** [comment] 2022-10-21 10:42
Hi Degiepet,
As there is no reply from your side. We think that the issue is resolved. 
So for now we are closing this issue. In case of any issues or this issue is reproduced again please create a new ticket for the same.

Thanks & Regards

**Closed by Nets-in-app** 2022-10-21 10:42 UTC
