### ISSUE TITLE
"unsupported URL" error when user doesn't have MobilePay app installed on the iphone.

### ISSUE THREAD

**Issue by mindtheworld** [Nets-eCom/Nets-Easy-iOS-SDK#28] opened 2022-06-14 21:39 UTC
**How to reproduce:**
1. Our solution is based on ReactNative. (Mia Bridge API used: https://github.com/Nets-eCom/Nets-Easy-iOS-SDK/blob/master/ReactNative/react-native-rn-mia/ios/RnMia.m)
2. Make sure 'MobilePay' app is not installed on the test iphone.
3. Select 'MobilePay' as payment option.

**Error is logged as showing below:**
![image](https://user-images.githubusercontent.com/34175635/173692438-bdb74dfb-6854-4d5c-a3a1-5db2014cca78.png)

It's working fine on android devices. (MobilePay webpage is loaded correctly with no error)

Any suggestion on how to fix the issue?  Thanks!

**Comment by BuildManager-Nets** [comment] 2022-06-16 12:58
Hi,
Just want to confirm are you configuring the Application LSApplicationQueriesSchemes for your app.
i.e <key>LSApplicationQueriesSchemes</key>
<array>
    <string>mobilepayonline</string>
    <string>mobilepayonline-test</string>
</array>

**Comment by BuildManager-Nets** [comment] 2022-06-21 13:10
Hi,
Could you please provide me more details for reproducing this issue.

**Comment by mindtheworld** [comment] 2022-06-23 09:42
1. run react native solution on an IOS device in live environment. 
2. make sure on that device, no "MobilePay" app installed.
3. select "MobilePay" as payment option after NetsEay payment window shows up.
4. insert phone number and confirm the payment.
5. error will occur when payment window tries to load moiblepay webpage.

**Comment by BuildManager-Nets** [comment] 2022-06-27 04:48
Thanks for steps.

Able to reproduce on our side. Soon I will get back to you.

**Comment by BuildManager-Nets** [comment] 2022-07-01 07:43
Hi, 
We have managed to reproduce the issue on our older SDK version (1.3.0) however it seems to have been resolved on 1.6.0.
Can you please make sure you are using our latest SDK and get back to us?

**Comment by BuildManager-Nets** [comment] 2022-07-12 05:19
Hi 
Apologies for the late reply.
The framework that you are using in the code currently just goes into the Mia. xcframework -> ios-arm64_armv7 folder -> plist file just check the parameter value

<key>CFBundleShortVersionString</key>
	<string>1.6.0</string>
	<key>CFBundleSupportedPlatforms</key> 

Thanks

**Comment by Miss-PiA** [comment] 2022-08-05 07:44
Hi,
Since there is no reply from your side we are closing this issue.
Don't hesitate to let us know further issues.

Thanks

**Comment by Nets-in-app** [comment] 2022-08-11 09:55
Hi,
Since there is no reply from your side we are closing this issue.
Don't hesitate to let us know further issues.

Thanks

**Comment by Nets-in-app** [comment] 2022-08-11 09:56
Hi,
Since there is no reply from your side we are closing this issue.
Don't hesitate to let us know further issues.

Thanks

**Closed by Nets-in-app** 2022-08-11 09:56 UTC
